create table if not exists public.audits (
  id bigint generated by default as identity primary key,
  business_name text not null,
  contact_name text not null,
  email text not null,
  phone text not null,
  industry text,
  employees text,
  answers jsonb not null default '[]'::jsonb,
  score integer not null check (score between 0 and 100),
  readiness_level text,
  status text not null default 'Audited',
  created_at timestamptz not null default now()
);

alter table public.audits enable row level security;

drop policy if exists "Public can submit audits" on public.audits;
create policy "Public can submit audits"
on public.audits
for insert
to anon, authenticated
with check (true);

-- Keep audit records private until HQ authentication is configured.
drop policy if exists "Authenticated HQ can view audits" on public.audits;
create policy "Authenticated HQ can view audits"
on public.audits
for select
to authenticated
using (true);
